name: Build in Azure Functions image & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-functions/python:4-python3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preflight (host.json + requirements.txt at repo root)
        run: |
          ls -la
          test -f host.json
          test -f requirements.txt
          head -n 20 requirements.txt || true

      - name: Install zip in container
        run: |
          apt-get update
          apt-get install -y zip

      - name: Vendor deps into .python_packages (inside AF image)
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt -t .python_packages/lib/site-packages
          PYTHONPATH=.python_packages/lib/site-packages python -c "import jinja2; print('vendored OK:', jinja2.__version__)"

      - name: Create deployment zip
        run: |
          zip -r release.zip . \
            -x ".git/*" ".github/*" ".venv/*" "venv/*" "__pycache__/*" ".pytest_cache/*" "*.PublishSettings" "local.settings.json"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: .

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "cvfa-pptx-acgjage0g8csb2cq"
          package: "release.zip"   # deploy the zip directly
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          respect-funcignore: true
