- name: Deploy to Azure Functions (Oryx remote build)
  uses: Azure/functions-action@v1
  with:
    app-name: cvfa-pptx-acgjage0g8csb2cq
    package: .
    publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
    scm-do-build-during-deployment: true
    enable-oryx-build: true
    remote-build: true
    respect-funcignore: true
