name: Build in Azure Functions image & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Build inside the SAME image Azure Functions uses → compatible wheels
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-functions/python:4-python3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify repo root (host.json + requirements.txt)
        run: |
          ls -la
          test -f host.json
          test -f requirements.txt

      - name: Vendor deps into .python_packages (inside Azure Functions image)
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt -t .python_packages/lib/site-packages
          python -c "import jinja2; print('vendored jinja2', jinja2.__version__)"

      - name: Create deployment zip
        run: |
          zip -r release.zip . \
            -x ".git/*" ".github/*" ".venv/*" "venv/*" "__pycache__/*" ".pytest_cache/*" "*.PublishSettings" "local.settings.json"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app

      - name: Unzip artifact
        run: unzip -q release.zip

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "cvfa-pptx-acgjage0g8csb2cq"
          package: "."
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          respect-funcignore: true
