name: Deploy Azure Functions (Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Vendor deps into .python_packages
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt -t .python_packages/lib/site-packages

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: cvfa-pptx-acgjage0g8csb2cq
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
