name: Build in Azure Functions image & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Build inside the SAME image Azure Functions uses → compatible wheels (no glibc issues)
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-functions/python:4-python3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preflight (host.json + requirements.txt at repo root)
        run: |
          ls -la
          test -f host.json
          test -f requirements.txt
          echo "requirements.txt (top):"
          head -n 20 requirements.txt || true

      - name: Vendor deps into .python_packages (inside AF image)
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt -t .python_packages/lib/site-packages
          # verify by adding .python_packages to PYTHONPATH
          PYTHONPATH=.python_packages/lib/site-packages \
          python -c "import jinja2, azure.functions, requests; print('vendored OK:', jinja2.__version__)"

      - name: Create deployment zip
        run: |
          zip -r release.zip . \
            -x ".git/*" ".github/*" ".venv/*" "venv/*" "__pycache__/*" ".pytest_cache/*" "*.PublishSettings" "local.settings.json"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app

      - name: Unzip artifact
        run: unzip -q release.zip

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "cvfa-pptx-acgjage0g8csb2cq"               # your Function App
          package: "."                                         # deploy the unzipped artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          respect-funcignore: true
