name: Deploy Azure Functions (Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Azure Functions (remote Oryx build on Kudu)
        uses: Azure/functions-action@v1
        with:
          app-name: cvfa-pptx-acgjage0g8csb2cq
          package: .              # repo root (host.json here)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
