name: Deploy Azure Functions (Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  PACKAGE_PATH: '.'   # repo root has host.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Show Python info
        run: |
          python -V
          pip -V

      - name: Vendor deps into .python_packages (for Azure Functions runtime)
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt -t .python_packages/lib/site-packages
          python - <<'PY'
import sys
print("✅ Vendored site-packages present:", ".python_packages/lib/site-packages" in str(sys.path))
import jinja2, azure.functions, requests
print("✅ jinja2", jinja2.__version__)
print("✅ azure.functions", azure.functions.__version__)
print("✅ requests", requests.__version__)
PY

      - name: Create deployment artifact
        run: |
          zip -r release.zip . \
            -x ".git/*" ".github/*" ".venv/*" "venv/*" "__pycache__/*" ".pytest_cache/*" "*.PublishSettings" "local.settings.json"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app

      - name: Unzip artifact
        run: unzip -q release.zip

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: cvfa-pptx-acgjage0g8csb2cq
          package: ${{ env.PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
